class BestBuyObjects:
    account_status_label = 'profileMenuWrap1'
    account_log_in_link = 'a.action-btn'
    account_log_out_link = 'logout-button'
    login_welcome_message = 'h1.cia-heading.cia-sign-on__heading'
    login_email_input = 'fld-e'
    login_password_input = 'fld-p1'
    login_submit_button = 'button.cia-form__submit-button.js-submit-button'
    product_add_to_cart_button = '//div[@id=\'pdp-add-to-cart-button\']/div/button'
    product_name_label = 'h1.type-subhead-alt-regular'
    product_sku_label = 'sku-value'
    product_price_label = 'div.pb-hero-price.pb-purchase-price > span'
    product_shipping_availability_label = 'span.ff-method-unavailable'
    product_pickup_availability_label = 'div.ff-description > span.ff-method-unavailable'
    popup_suggestion_box = 'div.modal-content-vcenter'
    popup_no_thanks_button = u"No, thanks. Go to cart ›"
    review_item_in_cart_title_label = 'h1.listing-header__title'
    review_change_zip_link = 'Update Location'
    review_change_zip_input = 'location'
    review_change_zip_button = 'button.btn.btn-primary'
    review_change_zip_close = 'button.pl-close'
    review_checkout_button = '(//button[@type=\'button\'])[2]'
    review_product_total_label = 'listing-footer__pricing-description'
    review_quantity_dropdown = 'select.item-quantity__select.form-control'
    review_radio_button_li = '/html/body/div[3]/div[2]/div/div[1]/div/div/span/div/div[3]/div/div[2]/div/div/div/div[' \
                             '1]/div[2]/form/ul/li'
    review_radio_button_2 = 'availability-radio-1'
    checkout_delivery_availability_label = 'div.fulfillment-group__unique-fulfillment-message'
    checkout_shipping_availability_label = '//div[@id=\'app\']/div/div/div[2]/div[2]/section/div/div/' \
                                           'section/fieldset/div/div[2]'
    cart_checkout_button = '(//button[@type=\'button\'])[2]'
    shipping_continue_button = '//*/button[contains(.,\'Continue to Payment Information\')]'
    loading_spinner = 'div.spinnable'
    large_spinner = 'spinner spinner-large'
    next_page_spinner = 'div.page-spinner.page-spinner--in'

